:page-layout: standard_toc
:page-title: Year 9 IST - Assignment Two
:icons: font


= Year 9 IST - Assignment Two (Semester Two) =

*Weight:* 30% +
*Due:* Tuesday 22 September 2020 (Week 10) by 8:45am

== Changelog ==

This assignment was last updated on *Wednesday 2 September 2020*.

== Project Overview ==

The major project requires you to design a game for the iPad that tells a story in order to raise awareness of historical, modern and/or fictional culture (with appropriate respect and sensitivity). This may include a range of social and ethical issues. Note that this is primarily a design project and you are not expected to implement all of it. You will be required, however, to plan a minigame prototype which you will implement for your final assignment.

=== Cultural Story Selection ===

Your story may be based on one of the following themes:

* Telling the story of influential historical events or people such as the story of Pemulwuy, an influential Aboriginal person known for his resistance to the European settlement of Australia which began with the arrival of the First Fleet in January 1788
* Describing the ideas and traditions of a cultural group, such as the hunter-gatherer lifestyle of the Ngunnawal people, who have been living in this land for at least 20,000 years
* Explaining the cultural significance of a festival or customs such as the Chinese Lunar New Year or Ramadan
* Exploring religious beliefs and practices such as contrasting different ideas about the afterlife, gods and/or religious ceremonies
* Other ideas that you may negotiate with the teacher

=== Appropriate respect and sensitivity ===

Please be aware that some topics may not be appropriate for your project if they are not approached with appropriate caution, respect and sensitivity.

For example, creating a game that teaches players how to speak the Ngunnawal language is very different from teaching players how to speak Chinese. This is because, "Ngunnawal, like many of the languages spoken across Australia for millennia, has been eroded by time, and by government policies that sought to disconnect its speakers from their country and their shared identity." (https://www.abc.net.au/news/2019-07-14/indigenous-language-needs-to-be-fostered-and-protected/11305682[Source: ABC Radio Canberra^])

Imagine if your entire culture and language were taken from you, and then the people responsible decided to teach about your culture and language as if it was their own. They could easily misrepresent things and unintentionally cause offence. You may like to read this article about https://au.reachout.com/articles/why-cultural-appropriation-isnt-cool[why cultural appropriation isn't cool^].

An appropriate first step for a project of this nature would be to seek the advice of a respected authority on the subject such as an Aboriginal elder or community representative.

If you are unsure about cultural respect and sensitivity, you should always ask your teacher for advice.

=== Minigame Designs ===

You will need to design and integrate 3-5 minigames into the story. These all need to be appropriately designed for use on an iPad. The expected format is:

* An interactive story, where players progress through a variety of SpriteKit Game Scenes
* Challenges in the form of minigames as you progress through the story
* Animations and/or text based story sequences in between minigames

=== Minigame Prototype Plan ===

You are required to create a detailed minigame prototype plan to describe the code you would need to write for one minigame that you will develop and include in your next assignment.

== Game Design Tips ==

According to this video about https://www.youtube.com/watch?v=G8AT01tuyrk[The Basic Principles of Game Design^], all good game designs rest upon a solid foundation with 3 pillars:

* *Direction* - The player's role and purpose
* *Communication* - How the role and purpose is communicated to the player
* *Appeal* - How the game is designed to appeal to players, without relying on the use of stunning graphics

The video then discusses a number of game design principles that help you to strengthen the pillars.

The video is loosely structured and based upon the ideas of this site: https://www.gamasutra.com/view/feature/132341/the_13_basic_principles_of_.php?page=2[The 13 Basic Principles of Game Design^]

== Deliverables ==

You are required to share a Google Doc with your teacher that includes 3 sections:

=== 1. Game Proposal (250-1000 words) ===

This should include:

* An appropriate story to tell and justification of why it's important to raise awareness *(short paragraph)*
* Research for the story with appropriate sources referenced correctly *(short paragraph with references)*
* A summary of how you will tell your story and raise awareness using an iPad game as the medium *(short paragraph)*
* A description of a completed sequence of story events that include minigames, animations and/or text-based descriptions *(short paragraph or bullet points)*

=== 2. Minigame Designs (250-1000 words) ===

For each of your minigames, you should include details about:

* Game mechanics *(bullet points)*
* Context and purpose within the story *(short paragraph)*
* How the minigame is designed to direct, communicate and appeal to players, referencing at least one game design principle *(short paragraph)*
* Steps a programmer would need to take to implement the minigame *(bullet/numbered points)*. For example, (1) Create a background (2) Create a player that moves using an onscreen D-Pad, etc.

=== 3. Minigame Prototype Plan (250-1000 words) ===

Your final assignment will involve you creating a version of your minigame prototype, so plan carefully!

Select the minigame that is most appropriate for you to develop based on your skill level. Then list and describe:

* The main functions that you need to consider when designing a SpriteKit Game Scene *(Headings plus one sentence description)*
* What variables you need to create and how they will be utilised for the minigame to function as designed *(bullet points)*
* What is meant to happen within each of the functions *(description of code / code comments)*

== Submission Instructions ==

This assignment is worth 30% of your Semester One assessment for this subject.

*Late submissions will incur penalties as per the school assessment policy:* Students will lose 10% of the total value of the assessment per day late, or part thereof.

=== Draft submissions ===

You may optionally (but strongly encouraged) submit one draft of your assignment for review prior to formal submission. Your draft must be feature complete (i.e. not a half-done assignment) and submitted at least one week before the assignment due date. To submit a draft email your teacher with a link to your Google Doc.

== Marking Guidelines ==

link:marking-guidelines.pdf[Your assignment will be marked following the criteria in this PDF file.^]

*Note:* These marking guidelines are subject to change/update &mdash; particularly if something is brought to our attention we didn't consider when writing the assignment. Any such updates will be highlighted in the changelog.

[#_academic_honesty]
== Academic Honesty

include::../common/academic_honesty.adoc[]
