:page-layout: standard_toc
:page-title: Year 9 IST - Assignment One
:icons: font

= Year 9 IST - Assignment One (Semester Two) =

*Weight:* 30% +
*Due:* Monday 6 September 2021 (Week 8) by 8:45am

== Changelog ==

This assignment was last updated on *Monday 23 August 2021*.

* *UPDATE MONDAY 23 AUGUST*: Included videos to demonstrate functionality of the website to replicate. Requirements and marking guidelines were revamped, reducing the overall scope and complexity of the website. Marks were also removed from the extension task component. These changes are a response to the impact of a short term and fast approaching deadlines, particularly during lockdown.

== Task Description ==

This assignment requires you to code a multipage website making use of Vue.js.

=== Your task ===

Below are the tasks you need to complete.

==== Navbar component & home page ====

You will need to create a navbar component using the composition API, which includes:

* Functional links which navigate to 3 pages: Home, Game & API
* Tha navigation bar should be styled as a horizontal menu using Bootstrap
* The currently selected page should be visible using conditional styling

You will also need to create a home page component, which includes:

* A title
* A label and input for the user to type in their name
* A button to save their name permanently
* The name should be stored permanently using local storage, and displayed permanently under the navbar until it is overwritten

A video is provided below showing you the functionality which you need to replicate:

video::navbar_home.mp4[width=882]

==== Game page ====

You will need to create a game component which includes:

* A title
* A paragraph to display a "How many...?" question
* A button to display an optional hint
* A paragraph to display the optional hint when the above button is clicked
* A heading and input to enter a guess
* A button to check the guess
* A heading and paragraph to display the result
* A heading and paragraph to display debugging details

The game needs to work by:

* Initialising a list of objects (e.g. bodies with bones) to be used for storing questions and answers. This should include 3 properties: name, answer and hint
* Displaying one of the objects randomly (using it's name) as part of the question (e.g. How many bones does an average *human* have?)
* An optional hint belonging to the random object should be displayed when the *Show hint* button is clicked
* The answer should be checked with the random object's answer, when the *Make a guess* button is clicked, displaying the result *Correct!* or *Incorrect!*
* Previous guesses should display a result of *You have already guessed [number]*
* A debugging section which should show the correct answer and previous guesses to make it easy to verify that it is functioning correctly

A video is provided below showing you the functionality which you need to replicate:

video::game.mp4[width=882]

==== API page ====

You will need to create an api component, which includes:

* A title
* A button to select a new random true/false question
* A paragraph to display the true/false question
* Two buttons to answer *true* or *false*
* A heading and paragraph to display the result
* Two paragraphs to display the tally of correct and incorrect answers
* A debugging section which should show the correct answer to make it easy to verify that it is functioning correctly

The api game needs to work by:

* Displaying a default true/false question with appropriate binding
* Calling a function with a 'true' or 'false' argument, to check the answer when either the *True* or *False* buttons are clicked
* The result of *Correct!* or *Incorrect!* needs to be displayed
* The correct and incorrect answers should increment whenever a correct or incorrect answer is guessed
* Whenever the *Get a new question* button is clicked, you update the question data by fetching a URL made up of an api of "https://opentdb.com/api.php" and a query of "?amount=1&type=boolean"
* All of the above functionality should work with any fetched questions

video::api.mp4[width=882]

=== Outcomes/Assessment Criteria ===

* 5.1.1 select and justify the application of appropriate software programs to a range of tasks
* 5.2.1 describe and apply problem-solving processes when creating solutions
* 5.2.2 design, produce and evaluate appropriate solutions to a range of challenging problems
* 5.2.3 critically analyse decision making processes in a range of information and software solutions

== Submission Instructions ==

This assignment is worth 30% of your Semester One assessment for this subject.

You will be provided with a template within the *Assessments* tab in EDSTEM called *Dynamic Website Replica*. All you need to do is complete the requirements using this workspace.

*Late submissions will incur penalties as per the school assessment policy.*

=== Draft submissions ===

You may optionally (but strongly encouraged) submit one draft of your assignment for review prior to formal submission. Your draft must be feature complete (i.e. not a half-done assignment) and submitted at least one week before the assignment due date - for this assignment, drafts are due by 8:45am on Monday 30 August 2021). To submit a draft email your teacher, stating that your work in EDSTEM is ready to be reviewed.

[#_marking_guidelines]
=== Marking Guidelines ===

link:marking-guidelines.pdf[Your assignment will be marked following the criteria in this PDF file.^]

*Note:* These marking guidelines are subject to change/update &mdash; particularly if something is brought to our attention we didn't consider when writing the assignment. Any such updates will be highlighted in the changelog.

[#_academic_honesty]
== Academic Honesty

include::../common/academic_honesty.adoc[]
